# Generated by Django 4.2.4 on 2023-08-22 00:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("board", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="created_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
