# Generated by Django 4.2.4 on 2023-08-17 07:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("board", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(max_length=32)),
                ("email", models.EmailField(max_length=128)),
                ("password", models.CharField(max_length=64)),
                ("register_date", models.DateField(auto_now_add=True)),
                ("desc", models.TextField()),
            ],
        ),
    ]
